# Generated by Django 6.0.3 on 2026-04-02 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('titulares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(max_length=6, unique=True)),
                ('provisional', models.CharField(max_length=6, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id_titular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='afiliaciones', to='titulares.titular')),
            ],
        ),
    ]
