# Generated by Django 5.2.1 on 2026-06-16 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliaciones', '0002_alter_afiliacion_id'),
        ('asesores', '0004_alter_asesor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliacion',
            name='id_asesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='afiliaciones', to='asesores.asesor'),
            preserve_default=False,
        ),
    ]
