# Generated by Django 6.0.3 on 2026-03-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('celular', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
