# Generated by Django 6.0.3 on 2026-03-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0002_asesor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesor',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
