# Generated by Django 5.2.1 on 2026-05-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0003_alter_asesor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
