# Generated by Django 6.0.3 on 2026-04-01 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(db_index=True, max_length=10, unique=True)),
                ('celular', models.CharField(max_length=10, null=True)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('id_municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titulares', to='ubicaciones.municipio')),
            ],
        ),
    ]
