# Generated by Django 5.2.1 on 2026-06-05 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asesores', '0004_alter_asesor_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Papeleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.IntegerField(choices=[(1, 'Contrato'), (2, 'Provisional'), (3, 'Recibo')])),
                ('valor', models.CharField(max_length=6, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_asignado', models.BooleanField(default=False)),
                ('id_asesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='papelerias', to='asesores.asesor')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='papelerias_creada', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='papelerias_actualizada', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
