# Generated by Django 5.2.1 on 2026-06-22 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0004_alter_asesor_id'),
        ('bodega', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='papeleria',
            name='valor',
            field=models.CharField(max_length=6),
        ),
        migrations.AddConstraint(
            model_name='papeleria',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'valor'), name='unique_tipo_documento_valor'),
        ),
    ]
