# Generated by Django 5.2.1 on 2026-07-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialista', models.CharField(max_length=150)),
                ('especialidad', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=250)),
                ('celular', models.CharField(max_length=50)),
                ('particular', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('fecha_inicio', models.DateField(null=True)),
                ('fecha_terminacion', models.DateField(null=True)),
                ('estado', models.BooleanField(default=False)),
                ('soporte', models.FileField(blank=True, null=True, upload_to='especialistas/')),
            ],
        ),
    ]
