# Generated by Django 5.2.1 on 2026-08-03 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('contrato', models.CharField(max_length=6)),
                ('afiliado', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=25)),
                ('celular', models.CharField(max_length=25)),
                ('municipio', models.CharField(max_length=50)),
                ('nombre_especialista', models.CharField(max_length=150)),
                ('especialidad', models.CharField(max_length=150)),
                ('estado_cita', models.IntegerField(choices=[(1, 'Consulta'), (2, 'Examen'), (3, 'Consulta y examen')], default=1)),
                ('fecha_cita', models.DateField()),
                ('hora', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=250)),
                ('observacion_cita', models.CharField(max_length=300)),
                ('particular', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Confirmado'), (3, 'Cancelado')], default=1)),
                ('observacion', models.CharField(max_length=200)),
                ('secretaria', models.CharField(max_length=100)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_creada', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_actualizada', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
