# Generated by Django 5.2.1 on 2026-08-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0002_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='celular',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='direccion',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_cita',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_registro',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='hora',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='identificacion',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='municipio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='nombre_especialista',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='observacion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='observacion_cita',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='particular',
            field=models.IntegerField(null=True),
        ),
    ]
