# Generated by Django 5.2.1 on 2026-05-26 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliaciones', '0002_alter_afiliacion_id'),
        ('asesores', '0004_alter_asesor_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recibo', models.DateField()),
                ('abono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('id_afiliacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aportes', to='afiliaciones.afiliacion')),
                ('id_asesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aportes', to='asesores.asesor')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aportes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
