# Generated by Django 6.0.3 on 2026-04-01 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=150)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='ubicaciones.departamento')),
            ],
        ),
    ]
